spring:
  config:
    import: optional:file:.env[.properties]
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

dataforseo:
  api:
    user: ${dataforseo.api.user}
    key: ${dataforseo.api.key}

seo-news:
  input-yml: classpath:dataforseo-queries.yml
  output-dir: output
