spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

batch:
  workdir: workdir
  siren:
    input-dir: ${batch.workdir}/01-siren
    done-dir: ${batch.workdir}/01-siren/done
    output-dir: ${batch.workdir}/02-siren-line
  company-enrich:
    input-dir: ${batch.workdir}/02-siren-line
    done-dir: ${batch.workdir}/02-siren-line/done
    company-output-dir: ${batch.workdir}/03-company
    contact-output-dir: ${batch.workdir}/04-contact
    relation-output-dir: ${batch.workdir}/05-relation
  search-news-distribute:
    company-input-dir: ${batch.workdir}/03-company
    company-done-dir: ${batch.workdir}/03-company/done
    company-output-dir: ${batch.workdir}/10-company-search-news
    person-input-dir: ${batch.workdir}/04-contact
    person-done-dir: ${batch.workdir}/04-contact/done
    person-output-dir: ${batch.workdir}/11-person-search-news
  company-news-search:
    input-dir: ${batch.workdir}/10-company-search-news
    done-dir: ${batch.workdir}/10-company-search-news/done
    output-dir: ${batch.workdir}/12-company-news




