server:
  port: 8080

spring:
  application:
    name: crm
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/crm}
    username: ${DB_USER:crm}
    password: ${DB_PASS:crm}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
